export enum BookingStatus {
  REQUESTED = "requested",
  CONFIRMED = "CONFIRMED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
  PARENT_NO_SHOW = "PARENT_NO_SHOW",
  NANNY_NO_SHOW = "NANNY_NO_SHOW",
}
